markdown: GFM
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: PORE | SE-677 | Documentation Site
description: Documentation site for quality assurance for a skin care iOS application
