name: PR Opened Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Check Spelling
      uses: check-spelling/check-spelling@v0.0.22      
        echo "PR opened! Running spell check"

    # Add more steps as needed
